set_property PACKAGE_PIN W4 [get_ports {an[3]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]
set_property PACKAGE_PIN U2 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]
set_property PACKAGE_PIN V17 [get_ports sw]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports btnC]
set_property IOSTANDARD LVCMOS33 [get_ports btnR]
set_property IOSTANDARD LVCMOS33 [get_ports btnU]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports sw]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btnc IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btnu IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btnr IBUF]

set_property PULLDOWN true [get_ports btnC]
set_property PULLDOWN true [get_ports btnR]
set_property PULLDOWN true [get_ports btnU]

create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B1_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B2_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B3_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B4_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SW1_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports B1]
set_property IOSTANDARD LVCMOS33 [get_ports B2]
set_property IOSTANDARD LVCMOS33 [get_ports B3]
set_property IOSTANDARD LVCMOS33 [get_ports B4]
set_property IOSTANDARD LVCMOS33 [get_ports B5]
set_property IOSTANDARD LVCMOS33 [get_ports SW1]
set_property IOSTANDARD LVCMOS33 [get_ports SW2]
set_property IOSTANDARD LVCMOS33 [get_ports SW3]
set_property PACKAGE_PIN V17 [get_ports SW1]
set_property PACKAGE_PIN V16 [get_ports SW2]
set_property PACKAGE_PIN W16 [get_ports SW3]
set_property PACKAGE_PIN U18 [get_ports B1]
set_property PACKAGE_PIN T18 [get_ports B2]
set_property PACKAGE_PIN T17 [get_ports B3]
set_property PACKAGE_PIN U17 [get_ports B4]
set_property PACKAGE_PIN W19 [get_ports B5]
set_property PULLDOWN true [get_ports B5]
set_property PULLDOWN true [get_ports B4]
set_property PULLDOWN true [get_ports B3]
set_property PULLDOWN true [get_ports B2]
set_property PULLDOWN true [get_ports B1]

set_property IOSTANDARD LVCMOS33 [get_ports p]
set_property PACKAGE_PIN L1 [get_ports p]

set_property IOSTANDARD LVCMOS33 [get_ports {mstate[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mstate[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sstate[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sstate[0]}]
set_property PACKAGE_PIN P1 [get_ports {mstate[1]}]
set_property PACKAGE_PIN N3 [get_ports {mstate[0]}]
set_property PACKAGE_PIN P3 [get_ports {sstate[1]}]
set_property PACKAGE_PIN U3 [get_ports {sstate[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports btwo]
set_property PACKAGE_PIN W3 [get_ports btwo]

set_property IOSTANDARD LVCMOS33 [get_ports SW4]
set_property PACKAGE_PIN W17 [get_ports SW4]

set_property IOSTANDARD LVCMOS33 [get_ports bthree]
set_property PACKAGE_PIN V3 [get_ports bthree]

set_property IOSTANDARD LVCMOS33 [get_ports alarmPeriod]
set_property IOSTANDARD LVCMOS33 [get_ports Buzzer]
set_property IOSTANDARD LVCMOS33 [get_ports RGBLEDs]
set_property PACKAGE_PIN J1 [get_ports Buzzer]



set_property PACKAGE_PIN H1 [get_ports RGBLEDs]

set_property PACKAGE_PIN V13 [get_ports alarmPeriod]
